// src/types.ts

import { CATEGORIES } from './constants';

/**
 * Represents a blog post author.
 */
export interface Author {
  name: string;
  avatarUrl: string;
  bio?: string;
}

/**
 * Defines the possible categories for a blog post, derived from a constant array
 * to ensure type safety and a single source of truth.
 */
export type Category = typeof CATEGORIES[number];

/**
 * Represents a single blog post.
 * The structure is based on the frontmatter from the markdown files.
 */
export interface Post {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  content: string; // This will hold the raw markdown content from the file.
  imageUrl: string;
  category: Category;
  tags: string[];
  author: Author; // The author object is joined during data fetching for convenience.
  publishedDate: string;
  readTime: number; // in minutes
}

/**
 * Represents the structured data for an SEO content plan,
 * typically generated by the Gemini AI model.
 */
export interface SeoPlan {
  title: string;
  primaryKeyword: string;
  relatedKeywords: string[];
  outline: {
    h1: string;
    h2s: {
      title: string;
      h3s: string[];
    }[];
  };
  metaDescription: string;
  internalLinkingIdeas: string[];
  schemaType: string;
}
